name: Core

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: |
        echo 'org.gradle.caching=true' >> gradle.properties
        echo 'org.gradle.parallel=true' >> gradle.properties
        echo 'org.gradle.vfs.watch=true' >> gradle.properties
        echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
        echo 'android.native.buildOutput=verbose' >> gradle.properties
        ./gradlew zipAll
    - name: Prepare artifact
      if: success()
      id: prepareArtifact
      run: |
        riruReleaseName=`ls core/release/LSPosed-v*-riru-release.zip | awk -F '(/|.zip)' '{print $3}'` && echo "::set-output name=riruReleaseName::$riruReleaseName"
        riruDebugName=`ls core/release/LSPosed-v*-riru-debug.zip | awk -F '(/|.zip)' '{print $3}'` && echo "::set-output name=riruDebugName::$riruDebugName"
        zygiskReleaseName=`ls core/release/LSPosed-v*-zygisk-release.zip | awk -F '(/|.zip)' '{print $3}'` && echo "::set-output name=zygiskReleaseName::$zygiskReleaseName"
        zygiskDebugName=`ls core/release/LSPosed-v*-zygisk-debug.zip | awk -F '(/|.zip)' '{print $3}'` && echo "::set-output name=zygiskDebugName::$zygiskDebugName"
        unzip core/release/LSPosed-v*-riru-release.zip -d LSPosed-riru-release
        unzip core/release/LSPosed-v*-riru-debug.zip -d LSPosed-riru-debug
        unzip core/release/LSPosed-v*-zygisk-release.zip -d LSPosed-zygisk-release
        unzip core/release/LSPosed-v*-zygisk-debug.zip -d LSPosed-zygisk-debug
    - name: Upload riru release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.prepareArtifact.outputs.riruReleaseName }}
        path: './LSPosed-riru-release/*'
    - name: Upload riru debug
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.prepareArtifact.outputs.riruDebugName }}
        path: './LSPosed-riru-debug/*'
    - name: Upload zygisk release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.prepareArtifact.outputs.zygiskReleaseName }}
        path: './LSPosed-zygisk-release/*'
    - name: Upload zygisk debug
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.prepareArtifact.outputs.zygiskDebugName }}
        path: './LSPosed-zygisk-debug/*'
    - name: Upload mappings
      uses: actions/upload-artifact@v2
      with:
        name: mappings
        path: |
          core/build/outputs/mapping/release
          app/build/outputs/mapping/release
    - name: Print Locations
      if: ${{ github.event_name != 'pull_request' && success() && github.ref == 'refs/heads/master' }}
      env:
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_URL: ${{ github.event.head_commit.url }}
      run: |
        OUTPUT="core/release/"
        echo "riruRelease=$(find $OUTPUT -name "LSPosed-v*-riru-release.zip")"
        echo "riruDebug=$(find $OUTPUT -name "LSPosed-v*-riru-debug.zip")"
        echo "zygiskRelease=$(find $OUTPUT -name "LSPosed-v*-zygisk-release.zip")"
        echo "zygiskDebug=$(find $OUTPUT -name "LSPosed-v*-zygisk-debug.zip")"
